(autoload 'yas/debug-snippet-vars               "yasnippet-debug" "" t)
(autoload 'yas/exterminate-package              "yasnippet-debug" "" t)
(autoload 'yas/debug-test                       "yasnippet-debug" "" t)
(autoload 'yas/direct-keymaps-reload            "yasnippet" "" t)
(autoload 'yas/minor-mode                       "yasnippet" "" t)
(autoload 'yas/minor-mode-on                    "yasnippet" "" t)
(autoload 'yas/global-mode                      "yasnippet" "" t)
(autoload 'snippet-mode                         "yasnippet" "" t)
(autoload 'yas/make-menu-binding                "yasnippet" "" t)
(autoload 'yas/load-directory                   "yasnippet" "" t)
(autoload 'yas/reload-all                       "yasnippet" "" t)
(autoload 'yas/compile-bundle                   "yasnippet" "" t)
(autoload 'yas/compile-textmate-bundle          "yasnippet" "" t)
(autoload 'yas/about                            "yasnippet" "" t)
(autoload 'yas/expand-from-trigger-key          "yasnippet" "" t)
(autoload 'yas/expand-from-keymap               "yasnippet" "" t)
(autoload 'yas/insert-snippet                   "yasnippet" "" t)
(autoload 'yas/visit-snippet-file               "yasnippet" "" t)
(autoload 'yas/new-snippet                      "yasnippet" "" t)
(autoload 'yas/find-snippets                    "yasnippet" "" t)
(autoload 'yas/load-snippet-buffer              "yasnippet" "" t)
(autoload 'yas/tryout-snippet                   "yasnippet" "" t)
(autoload 'yas/describe-tables                  "yasnippet" "" t)
(autoload 'yas/next-field-or-maybe-expand       "yasnippet" "" t)
(autoload 'yas/next-field                       "yasnippet" "" t)
(autoload 'yas/prev-field                       "yasnippet" "" t)
(autoload 'yas/abort-snippet                    "yasnippet" "" t)
(autoload 'yas/exit-snippet                     "yasnippet" "" t)
(autoload 'yas/exit-all-snippets                "yasnippet" "" t)
(autoload 'yas/skip-and-clear-or-delete-char    "yasnippet" "" t)

(autoload 'yas/initialize                       "yasnippet" "" nil) ;; Main entry
(provide 'yasnippet-epackage-install)
